services:
  rota-facil-database:
    image: postgis/postgis:16-3.4
    container_name: rota-facil-database
    environment:
      POSTGRES_DB: ${ROTA_FACIL_DATASOURCE_NAME}
      POSTGRES_USER: ${ROTA_FACIL_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${ROTA_FACIL_DATASOURCE_PASSWORD}
    ports:
      - 5432:5432

    volumes:
      - rota-facil-db-data:/var/lib/postgresql/data


  rota-facil-minio:
    image: minio/minio
    container_name: rota-facil-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin123}
    volumes:
      - minio-data:/data

volumes:
  rota-facil-db-data:
  minio-data:
