spring.datasource.url=${ROTA_FACIL_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rota_facil_database}
spring.datasource.username=${ROTA_FACIL_DATASOURCE_USERNAME:rota_facil}
spring.datasource.password=${ROTA_FACIL_DATASOURCE_PASSWORD:admin}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration
spring.flyway.log-resolvers=true